macos ci codesign

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -47,6 +47,16 @@ jobs:
         if: matrix.platform == 'web'
         run: dart run tools/fetch_web_dependencies.dart
 
+      - name: MacOS Code Signing 🍎
+        if: matrix.platform == 'macos'
+        run: |
+          cd macos
+          fastlane setup_match > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
+        env:
+          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
+          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
+
       - name: Code Generation 🧬
         run: dart run build_runner build --delete-conflicting-outputs
 
